os: Visual Studio 2015
platform:
- AnyCPU
- x86
- x64
configuration:
- Release
environment:
  NUGET_API_KEY:
    secure: iSkm19DNdKOLxxCvHiaKikWXy25ZMwGBKpv+EgEprliGl0qX5HtKohLmwJsLnx5O
  NUGET_API_URL: https://www.nuget.org/api/v2/package
  MYGET_API_KEY:
    secure: xhYvrWYPHdNI+mQD+f4Zu3baL7fqW+nO/hYXJdN070Lej8wpa6gfrLi1NGtnQlAs
  MYGET_API_URL: https://www.myget.org/F/core2d-nightly/api/v2/package
  CHOCOLATEY_API_KEY:
    secure: q7wW+4CR9k2KFifRGNEGpMuCQ5TPZLtwuQ8XLmNC1qP3jgHFzDU1KD+Z+MnFgUsW
  CHOCOLATEY_API_URL: https://chocolatey.org/
before_build:
- cmd: git submodule update --init
build_script:
- ps: .\build.ps1 -Target "AppVeyor" -Platform $env:platform -Configuration $env:configuration
test: off
notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/cc9eb0e869ca5a539718
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
artifacts:
  - path: artifacts\test-results\*.xml
  - path: artifacts\nuget\*.nupkg
  - path: artifacts\chocolatey\*.nupkg
  - path: artifacts\zip\*.zip
cache:
- packages -> src\**\packages.config, dependencies\**\packages.config, tests\**\packages.config
- tools -> build.cake, tools\packages.config
