os: Visual Studio 2015
platform:
- AnyCPU
- x86
- x64
configuration:
- Release
before_build:
- cmd: git submodule update --init
build_script:
- ps: .\build.ps1 -Target "AppVeyor" -Platform $env:platform -Configuration $env:configuration
test: off
notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/1ff736226b47ccf79930
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
artifacts:
  - path: test-results\*.xml
