version: '{build}'
image: Visual Studio 2017
skip_branch_with_pr: true
platform: Any CPU
configuration: Release
environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  NUGET_API_KEY:
    secure: iSkm19DNdKOLxxCvHiaKikWXy25ZMwGBKpv+EgEprliGl0qX5HtKohLmwJsLnx5O
  NUGET_API_URL: https://www.nuget.org/api/v2/package
  MYGET_API_KEY:
    secure: xhYvrWYPHdNI+mQD+f4Zu3baL7fqW+nO/hYXJdN070Lej8wpa6gfrLi1NGtnQlAs
  MYGET_API_URL: https://www.myget.org/F/core2d-nightly/api/v2/package
test: off
deploy: off
install:
  - if not exist dotnet-sdk-2.1.401-win-x64.exe appveyor DownloadFile https://download.microsoft.com/download/E/8/A/E8AF2EE0-5DDA-4420-A395-D1A50EEFD83E/dotnet-sdk-2.1.401-win-x64.exe -FileName "dotnet-sdk-2.1.401-win-x64.exe"
  - ps: Start-Process -FilePath "dotnet-sdk-2.1.401-win-x64.exe" -ArgumentList "/quiet" -Wait
  - cmd: dotnet --info
  - cmd: dotnet tool install -g Cake.Tool --version 0.30.0
build_script:
- cmd: dotnet cake build.cake -Target="AppVeyor" -Platform="%PLATFORM%" -Configuration="%CONFIGURATION%"
notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/1ff736226b47ccf79930
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
artifacts:
  - path: artifacts\nuget\*.nupkg
  - path: artifacts\zip\*.zip
cache:
  - dotnet-sdk-2.1.401-win-x64.exe
